CircularQueueMain: CircularQueue.o CircularQueueMain.o
	c++ CircularQueue.o CircularQueueMain.o -o CircularQueueMain

CircularQueue.o:CircularQueue.cpp
	c++ -c CircularQueue.cpp

CircularQueueMain.o: CircularQueueMain.cpp
	c++ -c CircularQueueMain.cpp

clean: rm CircularQueue.o CircularQueueMain.o
