Lab7: Person.o Student.o Employee.o Faculty.o Staff.o Lab7.o
	c++ Person.o Student.o Employee.o Faculty.o Staff.o Lab7.o -o Lab7

Person.o:Person.cpp
	c++ -c Person.cpp

Student.o:Student.cpp
	c++ -c Student.cpp

Employee.o:Employee.cpp
	c++ -c Employee.cpp

Faculty.o:Faculty.cpp
	c++ -c Faculty.cpp

Staff.o:Staff.cpp
	c++ -c Staff.cpp

Lab7.o:Lab7.cpp
	c++ -c Lab7.cpp

clean: rm Person.o Student.o Employee.o Faculty.o Staff.o Lab7.o
